name: Setup
description: Setup CI environment with pnpm cache
inputs:
  node-version:
    description: Version of node.js to install. Eg. 18.x, 21.7.4 etc
    default: 22.x
    required: false
runs:
  using: composite
  steps:
    - name: ✅ Checkout
      uses: actions/checkout@v4
    - uses: 🟡 pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false
    - name: 🟢 Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: 📦 Install dependencies
      shell: bash
      run: pnpm install -r
