name: CI

on:
  push:

permissions:
  contents: read

jobs:
  check-types:
    name: 🧪 check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run types:check
  check-format:
    name: 🧪 check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run format:check
  lint:
    name: 🧪 run eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run lint
